

logging:
  level:
    root: warn
    web: info
    com:
      example: debug



spring:
  datasource:
    username: postgres
    password: ${PASSWORD}
    url: jdbc:postgresql://localhost:5432/dacs
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true
#        jdbc:
#          time_zone: UTC
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  data:
    rest:
      base-path: /auto-api
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: true
  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000


token:
  secret:
    key: 48a868a4042f634ac04a117f00a87202131dd7c46c4b32c4acb3edc5e15f4511
  expirations: 3600000




